# Generated by Django 2.1.3 on 2018-11-13 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Companies index')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Companies name')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='People Index')),
                ('_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='People ID')),
                ('guid', models.CharField(blank=True, max_length=128, null=True, verbose_name='GUID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('has_died', models.BooleanField(default=False, verbose_name='Has this person died')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32, verbose_name='Balance')),
                ('picture', models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture')),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Eye Color')),
                ('gender', models.CharField(blank=True, max_length=16, null=True, verbose_name='Gender')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('registered', models.DateTimeField(blank=True, null=True, verbose_name='Registered')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags')),
                ('favourite_food', models.TextField(blank=True, null=True, verbose_name='Favourite Food')),
                ('favourite_fruit', models.TextField(blank=True, null=True, verbose_name='Favourite Fruit')),
                ('favourite_vegetable', models.TextField(blank=True, null=True, verbose_name='Favourite Vegetable')),
                ('greeting', models.TextField(blank=True, null=True, verbose_name='Greeting')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_staffs', to='api.Companies', verbose_name='Companies ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='frended', to='api.People')),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
