# Generated by Django 2.1.3 on 2018-11-13 05:52

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181113_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='favourite_fruits',
        ),
        migrations.AddField(
            model_name='people',
            name='favourite_fruits',
            field=api.models.ListField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='people',
            name='favourite_vegetables',
        ),
        migrations.AddField(
            model_name='people',
            name='favourite_vegetables',
            field=api.models.ListField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='people',
            name='tags',
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=api.models.ListField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
