# Generated by Django 2.1.3 on 2018-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181113_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='index',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
